FROM node:24-alpine

WORKDIR /app

COPY package*.json ./
# COPY bun.lock ./
RUN npm install

# Copy backend source code only (exclude web folder)
COPY src/ ./src/
COPY tsconfig.json ./
COPY drizzle/ ./drizzle/
COPY drizzle.config.ts ./

RUN npm run build

EXPOSE 3000

CMD ["node", "dist/main.js"]