services:
  db:
    image: postgres
    restart: always
    environment: 
      POSTGRES_USER: ndangdigarap
      POSTGRES_DB: ndangdigarap
      POSTGRES_PASSWORD: ndangdigarap
    ports:
      - 5441:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 5010:8080

volumes:
  pgdata:
