FROM node:18-alpine as builder

WORKDIR /app

COPY web/package*.json ./
COPY web/bun.lock ./
RUN npm install

COPY web/ .
RUN npm run build

FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/nginx.conf

# Expose port
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]